# register-supervisor.ps1 — install (or remove) the bot auto-start daemon.
#
# Windows-only. Creates a Scheduled Task "ClaudeBot-Supervisor" that runs
# scripts/supervisor.ps1 on TWO triggers:
#   - At Logon  : cold-starts the bot after a reboot / login (the daemon).
#   - Every 3m  : recurring liveness check (restart dead poller / cold-start).
#
# The task runs in the INTERACTIVE user session (LogonType Interactive) so the
# launched bot terminal window is visible and usable. The supervisor itself
# runs hidden; it only spawns a visible window when a (re)start is needed.
#
# Idempotent: re-running replaces the task. Single instance per tick is
# enforced by the supervisor's mutex AND by MultipleInstances=IgnoreNew here.
#
# Usage:
#   pwsh -File scripts\register-supervisor.ps1              # install
#   pwsh -File scripts\register-supervisor.ps1 -Unregister  # remove
#   pwsh -File scripts\register-supervisor.ps1 -IntervalMinutes 5

param(
    [switch]$Unregister,
    [int]$IntervalMinutes = 3,
    [string]$TaskName = 'ClaudeBot-Supervisor'
)

$ErrorActionPreference = 'Stop'
$repo       = Split-Path $PSScriptRoot -Parent
$supervisor = Join-Path $repo 'scripts\supervisor.ps1'

if ($Unregister) {
    try {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction Stop
        Write-Host "Removed scheduled task '$TaskName'." -ForegroundColor Yellow
    } catch {
        Write-Host "Task '$TaskName' not found / not removed: $($_.Exception.Message)" -ForegroundColor DarkGray
    }
    return
}

# Generate a VBS shim that launches the supervisor FULLY HIDDEN.
# Why: a scheduled task running pwsh.exe directly in the Interactive session
# flashes a console window every tick — `-WindowStyle Hidden` is honored only
# AFTER conhost has already drawn the window. wscript.exe is a GUI-subsystem
# host (no console of its own); WScript.Shell.Run(..., 0, False) starts pwsh
# with SW_HIDE before any window appears => zero flash.
#
# IMPORTANT: the VBS resolves pwsh at RUNTIME via the version-stable
# WindowsApps alias. A hardcoded versioned WindowsApps path breaks on EVERY
# PowerShell update and silently kills the supervisor.
$vbsPath = Join-Path $repo 'scripts\supervisor-hidden.vbs'
$vbs = @"
' Auto-generated by register-supervisor.ps1 — DO NOT EDIT.
' Runs the supervisor tick with no visible console (no flash).
' Resolves pwsh at RUNTIME via the version-stable WindowsApps alias; a
' hardcoded versioned path breaks on every PowerShell update.
Dim sh, fso, pwsh, cmd
Set sh = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
pwsh = sh.ExpandEnvironmentStrings("%LOCALAPPDATA%\Microsoft\WindowsApps\pwsh.exe")
If Not fso.FileExists(pwsh) Then pwsh = "pwsh.exe"
cmd = Chr(34) & pwsh & Chr(34) & " -NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File " & Chr(34) & "$supervisor" & Chr(34)
sh.Run cmd, 0, False
"@
Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII

$action = New-ScheduledTaskAction -Execute 'wscript.exe' `
    -Argument "`"$vbsPath`" //B //Nologo"

# Trigger 1: at logon (boot daemon). Trigger 2: repeat every N minutes forever.
$tLogon = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$tRepeat = New-ScheduledTaskTrigger -Once -At (Get-Date).Date.AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes)

# Interactive principal so the launched bot window shows in the user session.
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive -RunLevel Limited

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

Register-ScheduledTask -TaskName $TaskName -Action $action `
    -Trigger $tLogon, $tRepeat -Principal $principal -Settings $settings -Force | Out-Null

Write-Host "Registered '$TaskName':" -ForegroundColor Green
Write-Host "  - At Logon  -> cold-start the bot (boot daemon)" -ForegroundColor Cyan
Write-Host "  - Every ${IntervalMinutes}m -> liveness check (restart/cold-start as needed)" -ForegroundColor Cyan
Write-Host "  Runs (hidden, no flash): wscript $vbsPath -> pwsh -File $supervisor" -ForegroundColor DarkGray
Write-Host "  Remove with: pwsh -File scripts\register-supervisor.ps1 -Unregister" -ForegroundColor DarkGray
