# register-bot-supervisor.ps1 - install (or remove) the bot auto-start daemon.
#
# Creates a Windows Scheduled Task "AssistantBot-Supervisor" that runs
# scripts/bot-supervisor.ps1 on TWO triggers:
#   - At Logon  : cold-starts the bot after a reboot / login (the daemon).
#   - Every Nm  : recurring liveness check (restart dead poller / cold-start).
#
# The task runs in the INTERACTIVE user session (LogonType Interactive) so the
# bot's Windows Terminal window is visible and usable. The supervisor itself runs
# hidden; it only spawns the visible bot window when a (re)start is needed.
#
# Idempotent: re-running replaces the task. Single instance per tick is enforced
# by the supervisor's mutex AND by MultipleInstances=IgnoreNew here.
#
# Usage:
#   pwsh -File scripts\register-bot-supervisor.ps1              # install
#   pwsh -File scripts\register-bot-supervisor.ps1 -Unregister  # remove
#   pwsh -File scripts\register-bot-supervisor.ps1 -IntervalMinutes 5

param(
    [switch]$Unregister,
    [int]$IntervalMinutes = 3
)

$ErrorActionPreference = 'Stop'
$taskName   = 'AssistantBot-Supervisor'
# Repo root = parent of this scripts/ dir (no hardcoded user path).
$repo       = Split-Path -Parent $PSScriptRoot
$supervisor = Join-Path $repo 'scripts\bot-supervisor.ps1'

if ($Unregister) {
    try {
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction Stop
        Write-Host "Removed scheduled task '$taskName'." -ForegroundColor Yellow
    } catch {
        Write-Host "Task '$taskName' not found / not removed: $($_.Exception.Message)" -ForegroundColor DarkGray
    }
    return
}

# Resolve pwsh.exe (prefer 7; fall back to its WindowsApps alias, then 5.1).
$pwshExe = (Get-Command pwsh.exe -ErrorAction SilentlyContinue).Source
if (-not $pwshExe) {
    $alias = Join-Path $env:LOCALAPPDATA 'Microsoft\WindowsApps\pwsh.exe'
    $pwshExe = if (Test-Path $alias) { $alias } else { 'powershell.exe' }
}

# Generate a VBS shim that launches the supervisor FULLY HIDDEN.
# Why: a scheduled task running pwsh.exe directly in the Interactive session
# flashes a console window every tick - `-WindowStyle Hidden` is honored only
# AFTER conhost has already drawn the window. wscript.exe is a GUI-subsystem host
# (no console of its own); WScript.Shell.Run(..., 0, False) starts pwsh with
# SW_HIDE before any window appears => zero flash. A cold-start WT window
# (deliberately visible) is still spawned by the supervisor when needed.
$vbsPath = Join-Path $repo 'scripts\bot-supervisor-hidden.vbs'
$vbs = @"
' Auto-generated by register-bot-supervisor.ps1 - DO NOT EDIT.
' Runs the bot supervisor tick with no visible console (no flash).
Dim sh, cmd
Set sh = CreateObject("WScript.Shell")
cmd = Chr(34) & "$pwshExe" & Chr(34) & " -NoProfile -NonInteractive -ExecutionPolicy Bypass -WindowStyle Hidden -File " & Chr(34) & "$supervisor" & Chr(34)
sh.Run cmd, 0, False
"@
Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII

$action = New-ScheduledTaskAction -Execute 'wscript.exe' `
    -Argument "`"$vbsPath`" //B //Nologo"

# Trigger 1: at logon (boot daemon). Trigger 2: repeat every N minutes forever.
$tLogon = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$tRepeat = New-ScheduledTaskTrigger -Once -At (Get-Date).Date.AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes)

# Interactive principal so the launched bot WT window shows in the user session.
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive -RunLevel Limited

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

Register-ScheduledTask -TaskName $taskName -Action $action `
    -Trigger $tLogon, $tRepeat -Principal $principal -Settings $settings -Force | Out-Null

Write-Host "Registered '$taskName':" -ForegroundColor Green
Write-Host "  - At Logon  -> cold-start the bot (boot daemon)" -ForegroundColor Cyan
Write-Host "  - Every ${IntervalMinutes}m -> liveness check (restart/cold-start as needed)" -ForegroundColor Cyan
Write-Host "  Runs (hidden, no flash): wscript $vbsPath -> $pwshExe -File $supervisor" -ForegroundColor DarkGray
Write-Host "  Remove with: pwsh -File scripts\register-bot-supervisor.ps1 -Unregister" -ForegroundColor DarkGray
